CREATE SCHEMA IF NOT EXISTS inep;
CREATE TABLE IF NOT EXISTS inep.dim_regiao_ies (
    CO_REGIAO_IES NUMERIC(2),
    NO_REGIAO_IES CHAR(20),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_uf_ies (
    CO_UF_IES NUMERIC(2),
    NO_UF_IES CHAR(50),
    SG_UF_IES CHAR(2),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_municipio_ies (
    CO_MUNICIPIO_IES NUMERIC(7),
    NO_MUNICIPIO_IES CHAR(150),
    IN_CAPITAL_IES NUMERIC(2),
    CO_CAPITAL_IES CHAR(10),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_mesorregiao_ies (
    CO_MESORREGIAO_IES NUMERIC(4),
    NO_MESORREGIAO_IES CHAR(100),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_microrregiao_ies (
    CO_MICRORREGIAO_IES NUMERIC(5),
    NO_MICRORREGIAO_IES CHAR(100),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_organizacao_academica_ies (
    CO_ORGANIZACAO_ACADEMICA NUMERIC(1),
    TP_ORGANIZACAO_ACADEMICA CHAR(100),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_categoria_administrativa_ies (
    CO_CATEGORIA_ADMINISTRATIVA NUMERIC(1),
    TP_CATEGORIA_ADMINISTRATIVA CHAR(50),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_mantenedora_ies (
    CO_MANTENEDORA NUMERIC(8),
    NO_MANTENEDORA CHAR(100),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_ies (
    CO_IES NUMERIC(8),
    NO_IES CHAR(200),
    SG_IES CHAR(20),
    DS_ENDERECO_IES CHAR(255),
    DS_NUMERO_ENDERECO_IES CHAR(10),
    DS_COMPLEMENTO_ENDERECO_IES CHAR(20),
    NO_BAIRRO_IES CHAR(50),
    NU_CEP_IES NUMERIC(8),
    CO_REGIAO_IES NUMERIC(2),
    CO_UF_IES NUMERIC(2),
    CO_MUNICIPIO_IES NUMERIC(7),
    CO_MESORREGIAO_IES NUMERIC(4),
    CO_MICRORREGIAO_IES NUMERIC(5),
    TP_ORGANIZACAO_ACADEMICA NUMERIC(1),
    TP_CATEGORIA_ADMINISTRATIVA NUMERIC(1),
    CO_MANTENEDORA NUMERIC(8),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_infraestrutura_ies (
    CO_IES NUMERIC(8),
    IN_ACESSO_PORTAL_CAPES NUMERIC(1),
    IN_ACESSO_OUTRAS_BASES NUMERIC(1),
    IN_ASSINA_OUTRA_BASE NUMERIC(1),
    IN_REPOSITORIO_INSTITUCIONAL NUMERIC(1),
    IN_BUSCA_INTEGRADA NUMERIC(1),
    IN_SERVICO_INTERNET NUMERIC(1),
    IN_PARTICIPA_REDE_SOCIAL NUMERIC(1),
    IN_CATALOGO_ONLINE NUMERIC(1),
    QT_PERIODICO_ELETRONICO NUMERIC(8),
    QT_LIVRO_ELETRONICO NUMERIC(8),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.fato_tecnico_administrativo_ies (
    CO_IES NUMERIC(8),
    QT_TEC_TOTAL NUMERIC(8),
    QT_TEC_FUNDAMENTAL_INCOMP_FEM NUMERIC(8),
    QT_TEC_FUNDAMENTAL_INCOMP_MASC NUMERIC(8),
    QT_TEC_FUNDAMENTAL_COMP_FEM NUMERIC(8),
    QT_TEC_FUNDAMENTAL_COMP_MASC NUMERIC(8),
    QT_TEC_MEDIO_FEM NUMERIC(8),
    QT_TEC_MEDIO_MASC NUMERIC(8),
    QT_TEC_SUPERIOR_FEM NUMERIC(8),
    QT_TEC_SUPERIOR_MASC NUMERIC(8),
    QT_TEC_ESPECIALIZACAO_FEM NUMERIC(8),
    QT_TEC_ESPECIALIZACAO_MASC NUMERIC(8),
    QT_TEC_MESTRADO_FEM NUMERIC(8),
    QT_TEC_MESTRADO_MASC NUMERIC(8),
    QT_TEC_DOUTORADO_FEM NUMERIC(8),
    QT_TEC_DOUTORADO_MASC NUMERIC(8),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.fato_docente_ies (
    CO_IES NUMERIC(8),
    QT_DOC_TOTAL NUMERIC(8),
    QT_DOC_EXE NUMERIC(8),
    QT_DOC_EX_FEMI NUMERIC(8),
    QT_DOC_EX_MASC NUMERIC(8),
    QT_DOC_EX_SEM_GRAD NUMERIC(8),
    QT_DOC_EX_GRAD NUMERIC(8),
    QT_DOC_EX_ESP NUMERIC(8),
    QT_DOC_EX_MEST NUMERIC(8),
    QT_DOC_EX_DOUT NUMERIC(8),
    QT_DOC_EX_INT NUMERIC(8),
    QT_DOC_EX_INT_DE NUMERIC(8),
    QT_DOC_EX_INT_SEM_DE NUMERIC(8),
    QT_DOC_EX_PARC NUMERIC(8),
    QT_DOC_EX_HOR NUMERIC(8),
    QT_DOC_EX_0_29 NUMERIC(8),
    QT_DOC_EX_30_34 NUMERIC(8),
    QT_DOC_EX_35_39 NUMERIC(8),
    QT_DOC_EX_40_44 NUMERIC(8),
    QT_DOC_EX_45_49 NUMERIC(8),
    QT_DOC_EX_50_54 NUMERIC(8),
    QT_DOC_EX_55_59 NUMERIC(8),
    QT_DOC_EX_60_MAIS NUMERIC(8),
    QT_DOC_EX_BRANCA NUMERIC(8),
    QT_DOC_EX_PRETA NUMERIC(8),
    QT_DOC_EX_PARDA NUMERIC(8),
    QT_DOC_EX_AMARELA NUMERIC(8),
    QT_DOC_EX_INDIGENA NUMERIC(8),
    QT_DOC_EX_COR_ND NUMERIC(8),
    QT_DOC_EX_BRA NUMERIC(8),
    QT_DOC_EX_EST NUMERIC(8),
    QT_DOC_EX_COM_DEFICIENCIA NUMERIC(8),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_regiao_curso_ies (
    CO_REGIAO NUMERIC(2),
    NO_REGIAO CHAR(20),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_uf_curso_ies (
    CO_UF NUMERIC(2),
    SG_UF CHAR(2),
    NO_UF CHAR(50),
    CO_REGIAO NUMERIC(2),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_municipio_curso_ies (
    CO_MUNICIPIO NUMERIC(7),
    NO_MUNICIPIO CHAR(150),
    CO_UF NUMERIC(2),
    CO_CAPITAL NUMERIC(2),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_curso_ies (
    CO_CURSO NUMERIC(8),
    CO_REGIAO NUMERIC(2),
    CO_UF NUMERIC(2),
    CO_MUNICIPIO NUMERIC(7),
    CO_IES NUMERIC(8),
    CO_GRAU_ACADEMICO NUMERIC(1),
    TP_GRAU_ACADEMICO CHAR(100),
    TP_MODALIDADE_ENSINO NUMERIC(1),
    TP_NIVEL_ACADEMICO NUMERIC(1),
    CO_CINE_ROTULO CHAR(7),
    NO_CINE_ROTULO CHAR(120),
    CO_CINE_AREA_GERAL CHAR(2),
    CO_CINE_AREA_ESPECIFICA CHAR(3),
    CO_CINE_AREA_DETALHADA CHAR(4),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_cine_area_curso_ies (
    CO_CINE_AREA_GERAL CHAR(2),
    NO_CINE_AREA_GERAL CHAR(120),
    CO_CINE_AREA_ESPECIFICA CHAR(3),
    NO_CINE_AREA_ESPECIFICA CHAR(120),
    CO_CINE_AREA_DETALHADA CHAR(4),
    NO_CINE_AREA_DETALHADA CHAR(120),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_grau_academico_curso_ies (
    CO_GRAU_ACADEMICO NUMERIC(1),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_modalidade_ensino_curso_ies (
    TP_MODALIDADE_ENSINO NUMERIC(1),
    DESCRICAO_MODALIDADE CHAR(50),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.dim_nivel_academico_curso_ies (
    TP_NIVEL_ACADEMICO NUMERIC(1),
    DESCRICAO_NIVEL CHAR(50),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.fato_ingressante_desvinculado_curso_ies (
    CO_CURSO NUMERIC(8),
    ANO NUMERIC(4),
    QT_INGRESSANTE_TOTAL NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_TOTAL NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_FEM NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_MASC NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_SEM_DEFICIENCIA NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_COM_DEFICIENCIA NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_BRANCA NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_PRETA NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_PARDA NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_AMARELA NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_INDIGENA NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_COR_ND NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_BRA NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_EST NUMERIC(8),
    QT_INGRESSANTE_SEM_VINCULO_NAO_INFORMADO NUMERIC(8),
    ANO_CENSO NUMERIC(4)
);

CREATE TABLE IF NOT EXISTS inep.fato_matricula_ies (
    CO_IES NUMERIC(8),
    CO_CURSO NUMERIC(8),
    ANO NUMERIC(4),
    QT_MATRICULA_TOTAL NUMERIC(8),
    QT_MATRICULA_FEMININO NUMERIC(8),
    QT_MATRICULA_MASCULINO NUMERIC(8),
    QT_MATRICULA_TURNO_DIURNO NUMERIC(8),
    QT_MATRICULA_TURNO_NOTURNO NUMERIC(8),
    QT_MATRICULA_ATE_17 NUMERIC(8),
    QT_MATRICULA_18_24 NUMERIC(8),
    QT_MATRICULA_25_29 NUMERIC(8),
    QT_MATRICULA_30_34 NUMERIC(8),
    QT_MATRICULA_35_39 NUMERIC(8),
    QT_MATRICULA_40_49 NUMERIC(8),
    QT_MATRICULA_50_59 NUMERIC(8),
    QT_MATRICULA_60_MAIS NUMERIC(8),
    QT_MATRICULA_BRANCA NUMERIC(8),
    QT_MATRICULA_PRETA NUMERIC(8),
    QT_MATRICULA_PARDA NUMERIC(8),
    QT_MATRICULA_AMARELA NUMERIC(8),
    QT_MATRICULA_INDIGENA NUMERIC(8),
    QT_MATRICULA_COR_ND NUMERIC(8),
    ANO_CENSO NUMERIC(4)
);
